/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DataRightsRouteImport } from './routes/data-rights'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LockerRouteImport } from './routes/locker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as TacticsRouteImport } from './routes/tactics'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TrajectoryRouteImport } from './routes/trajectory'
import { Route as ApiBotsRouteImport } from './routes/api/bots'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiInventoryRouteImport } from './routes/api/inventory'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInventoryLiveRouteImport } from './routes/api/inventory.live'
import { Route as ApiInventoryStreamRouteImport } from './routes/api/inventory.stream'
import { Route as ApiOrdersIdRouteImport } from './routes/api/orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRightsRoute = DataRightsRouteImport.update({
  id: '/data-rights',
  path: '/data-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerRoute = LockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsRoute = TacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajectoryRoute = TrajectoryRouteImport.update({
  id: '/trajectory',
  path: '/trajectory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsRoute = ApiBotsRouteImport.update({
  id: '/api/bots',
  path: '/api/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryRoute = ApiInventoryRouteImport.update({
  id: '/api/inventory',
  path: '/api/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryLiveRoute = ApiInventoryLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ApiInventoryRoute,
} as any)
const ApiInventoryStreamRoute = ApiInventoryStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiInventoryRoute,
} as any)
const ApiOrdersIdRoute = ApiOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/data-rights': typeof DataRightsRoute
  '/faq': typeof FaqRoute
  '/lab': typeof LabRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRoute
  '/specs': typeof SpecsRoute
  '/tactics': typeof TacticsRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/trajectory': typeof TrajectoryRoute
  '/api/bots': typeof ApiBotsRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/inventory': typeof ApiInventoryRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inventory/live': typeof ApiInventoryLiveRoute
  '/api/inventory/stream': typeof ApiInventoryStreamRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/data-rights': typeof DataRightsRoute
  '/faq': typeof FaqRoute
  '/lab': typeof LabRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRoute
  '/specs': typeof SpecsRoute
  '/tactics': typeof TacticsRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/trajectory': typeof TrajectoryRoute
  '/api/bots': typeof ApiBotsRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/inventory': typeof ApiInventoryRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inventory/live': typeof ApiInventoryLiveRoute
  '/api/inventory/stream': typeof ApiInventoryStreamRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/data-rights': typeof DataRightsRoute
  '/faq': typeof FaqRoute
  '/lab': typeof LabRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRoute
  '/specs': typeof SpecsRoute
  '/tactics': typeof TacticsRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/trajectory': typeof TrajectoryRoute
  '/api/bots': typeof ApiBotsRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/inventory': typeof ApiInventoryRouteWithChildren
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/inventory/live': typeof ApiInventoryLiveRoute
  '/api/inventory/stream': typeof ApiInventoryStreamRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/data-rights'
    | '/faq'
    | '/lab'
    | '/locker'
    | '/login'
    | '/privacy'
    | '/returns'
    | '/shop'
    | '/specs'
    | '/tactics'
    | '/teams'
    | '/terms'
    | '/track'
    | '/trajectory'
    | '/api/bots'
    | '/api/catalog'
    | '/api/inventory'
    | '/api/orders'
    | '/api/session'
    | '/product/$slug'
    | '/api/auth/$'
    | '/api/inventory/live'
    | '/api/inventory/stream'
    | '/api/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/data-rights'
    | '/faq'
    | '/lab'
    | '/locker'
    | '/login'
    | '/privacy'
    | '/returns'
    | '/shop'
    | '/specs'
    | '/tactics'
    | '/teams'
    | '/terms'
    | '/track'
    | '/trajectory'
    | '/api/bots'
    | '/api/catalog'
    | '/api/inventory'
    | '/api/orders'
    | '/api/session'
    | '/product/$slug'
    | '/api/auth/$'
    | '/api/inventory/live'
    | '/api/inventory/stream'
    | '/api/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/data-rights'
    | '/faq'
    | '/lab'
    | '/locker'
    | '/login'
    | '/privacy'
    | '/returns'
    | '/shop'
    | '/specs'
    | '/tactics'
    | '/teams'
    | '/terms'
    | '/track'
    | '/trajectory'
    | '/api/bots'
    | '/api/catalog'
    | '/api/inventory'
    | '/api/orders'
    | '/api/session'
    | '/product/$slug'
    | '/api/auth/$'
    | '/api/inventory/live'
    | '/api/inventory/stream'
    | '/api/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DataRightsRoute: typeof DataRightsRoute
  FaqRoute: typeof FaqRoute
  LabRoute: typeof LabRoute
  LockerRoute: typeof LockerRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShopRoute: typeof ShopRoute
  SpecsRoute: typeof SpecsRoute
  TacticsRoute: typeof TacticsRoute
  TeamsRoute: typeof TeamsRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  TrajectoryRoute: typeof TrajectoryRoute
  ApiBotsRoute: typeof ApiBotsRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiInventoryRoute: typeof ApiInventoryRouteWithChildren
  ApiOrdersRoute: typeof ApiOrdersRouteWithChildren
  ApiSessionRoute: typeof ApiSessionRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-rights': {
      id: '/data-rights'
      path: '/data-rights'
      fullPath: '/data-rights'
      preLoaderRoute: typeof DataRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker': {
      id: '/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof LockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics': {
      id: '/tactics'
      path: '/tactics'
      fullPath: '/tactics'
      preLoaderRoute: typeof TacticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trajectory': {
      id: '/trajectory'
      path: '/trajectory'
      fullPath: '/trajectory'
      preLoaderRoute: typeof TrajectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots': {
      id: '/api/bots'
      path: '/api/bots'
      fullPath: '/api/bots'
      preLoaderRoute: typeof ApiBotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory': {
      id: '/api/inventory'
      path: '/api/inventory'
      fullPath: '/api/inventory'
      preLoaderRoute: typeof ApiInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/live': {
      id: '/api/inventory/live'
      path: '/live'
      fullPath: '/api/inventory/live'
      preLoaderRoute: typeof ApiInventoryLiveRouteImport
      parentRoute: typeof ApiInventoryRoute
    }
    '/api/inventory/stream': {
      id: '/api/inventory/stream'
      path: '/stream'
      fullPath: '/api/inventory/stream'
      preLoaderRoute: typeof ApiInventoryStreamRouteImport
      parentRoute: typeof ApiInventoryRoute
    }
    '/api/orders/$id': {
      id: '/api/orders/$id'
      path: '/$id'
      fullPath: '/api/orders/$id'
      preLoaderRoute: typeof ApiOrdersIdRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
  }
}

interface ApiInventoryRouteChildren {
  ApiInventoryLiveRoute: typeof ApiInventoryLiveRoute
  ApiInventoryStreamRoute: typeof ApiInventoryStreamRoute
}

const ApiInventoryRouteChildren: ApiInventoryRouteChildren = {
  ApiInventoryLiveRoute: ApiInventoryLiveRoute,
  ApiInventoryStreamRoute: ApiInventoryStreamRoute,
}

const ApiInventoryRouteWithChildren = ApiInventoryRoute._addFileChildren(
  ApiInventoryRouteChildren,
)

interface ApiOrdersRouteChildren {
  ApiOrdersIdRoute: typeof ApiOrdersIdRoute
}

const ApiOrdersRouteChildren: ApiOrdersRouteChildren = {
  ApiOrdersIdRoute: ApiOrdersIdRoute,
}

const ApiOrdersRouteWithChildren = ApiOrdersRoute._addFileChildren(
  ApiOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DataRightsRoute: DataRightsRoute,
  FaqRoute: FaqRoute,
  LabRoute: LabRoute,
  LockerRoute: LockerRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShopRoute: ShopRoute,
  SpecsRoute: SpecsRoute,
  TacticsRoute: TacticsRoute,
  TeamsRoute: TeamsRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  TrajectoryRoute: TrajectoryRoute,
  ApiBotsRoute: ApiBotsRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiInventoryRoute: ApiInventoryRouteWithChildren,
  ApiOrdersRoute: ApiOrdersRouteWithChildren,
  ApiSessionRoute: ApiSessionRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
